language: perl
perl:
  - "5.24"

jdk:
  - openjdk7

install:
  - jdk_switcher use openjdk7
  - (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan
  - cpan install Carton
  - carton install
  - ./init.sh

script:
  - cd framework/test
  - ./test_all_parallelized.sh
